### ISSUE TITLE
about code open-sourcing 

### ISSUE THREAD

**Issue by Usama1002** [Haoran-SONG/PiP-Planning-informed-Prediction#1]
Hi,

Thanks for the wonderful work. When is the code coming?

Best,

Usama.

**Comment by Haoran-SONG** [comment]
Hi Usama, 
I will release the codebase when I can spare some time within these TWO weeks. Thanks for your interest on our work. 
Best,
Haoran

**Comment by Haoran-SONG** [comment]
> Hi,
> 
> Thanks for the wonderful work. When is the code coming?
> 
> Best,
> 
> Usama.

Hi Usama,
I will release the codebase when I can spare some time within these TWO weeks. Thanks for your interest on our work.
Best,
Haoran

**Comment by Haoran-SONG** [comment]
> Hi,
> 
> Thanks for the wonderful work. When is the code coming?
> 
> Best,
> 
> Usama.

Fell sorry to tell you that the code releasing date would be postponed to the end of November as I'm recently busy preparing another paper submission. I'll release the codebase very soon after that deadline. Thanks for your understanding.

Sincerely, 
Haoran
