### ISSUE TITLE
The compressed package of the training model is damaged and cannot be decompressed

### ISSUE THREAD

**Issue by xiongcj123** [Haoran-SONG/PiP-Planning-informed-Prediction#11]
In the trained model you provided, the tar file in the downloaded file cannot be decompressed

**Comment by Haoran-SONG** [comment]
> In the trained model you provided, the tar file in the downloaded file cannot be decompressed

https://github.com/Haoran-SONG/PiP-Planning-informed-Prediction/issues/7#issuecomment-835161911
