### ISSUE TITLE
Looking forward to open source

### ISSUE THREAD

**Issue by mengqingyu123** [Haoran-SONG/PiP-Planning-informed-Prediction#2]
Very good work! Looking forward to your open source, I hope to learn something!

**Comment by Haoran-SONG** [comment]
> Very good work! Looking forward to your open source, I hope to learn something!

to be released in 24 hours. Feel sorry about that.

**Comment by mengqingyu123** [comment]
> > Very good work! Looking forward to your open source, I hope to learn something!
> 
> to be released in 24 hours. Feel sorry about that.

You are so kind! Open source itself is a very subjective thing. I am very happy to learn the specific implementation of the algorithm in your paper. Thanks again!
