### ISSUE TITLE
About NGSIM dataset

### ISSUE THREAD

**Issue by paller123** [Haoran-SONG/PiP-Planning-informed-Prediction#3]
I'm sorry to bother you，It seems that the data I downloaded from the [NGSIM](https://data.transportation.gov/Automobiles/Next-Generation-Simulation-NGSIM-Vehicle-Trajector)  is not complete. Could you send me a copy of your original data：us101-0750am-0805am-0820am-0835am.txt , i80-0400-0415.txt and i80-0500-0515-0530.txt.
Thank you so much!

**Comment by Haoran-SONG** [comment]
> I'm sorry to bother you，It seems that the data I downloaded from the [NGSIM](https://data.transportation.gov/Automobiles/Next-Generation-Simulation-NGSIM-Vehicle-Trajector) is not complete. Could you send me a copy of your original data：us101-0750am-0805am-0820am-0835am.txt , i80-0400-0415.txt and i80-0500-0515-0530.txt.
> Thank you so much!

I'm going to add a link for accessing the raw datasets and preprocessed ones. Thanks for your attention to our work. 

Best, 
Haoran

**Comment by paller123** [comment]
You are so kind!Thank you so much!

**Comment by paller123** [comment]
Sorry for disturbing you again.
 :( I‘m sorry maybe you didn't understand what I mean. I think there is a problem with the data I downloaded from the website .So ,Could you please  upload the raw datasets to  OneDrive?

**Comment by Haoran-SONG** [comment]
> Sorry for disturbing you again.
> :( I‘m sorry maybe you didn't understand what I mean. I think there is a problem with the data I downloaded from the website .So ,Could you please upload the raw datasets to OneDrive?

Just uploaded the raw files [here](https://hkustconnect-my.sharepoint.com/:f:/g/personal/hsongad_connect_ust_hk/Evo9MNDPLhZAn-ygM1-GOVQB-ULdHzx4WurTZ1j-Bk_JNQ?e=YdG7Xk). Please check it.

**Comment by paller123** [comment]
Sorry but this link seems to be the Processed datasets  :(
[https://hkustconnect-my.sharepoint.com/:f:/g/personal/hsongad_connect_ust_hk/Evo9MNDPLhZAn-ygM1-GOVQB-ULdHzx4WurTZ1j-Bk_JNQ?e=YdG7Xk](url)
Maybe it hasn't been uploaded yet?

**Comment by Haoran-SONG** [comment]
> Sorry but this link seems to be the Processed datasets :(
> [https://hkustconnect-my.sharepoint.com/:f:/g/personal/hsongad_connect_ust_hk/Evo9MNDPLhZAn-ygM1-GOVQB-ULdHzx4WurTZ1j-Bk_JNQ?e=YdG7Xk](url)
> Maybe it hasn't been uploaded yet?

Oh sorry, the uploading process was interrupted unexpectedly. Now It's right there.
