### ISSUE TITLE
数据集下载解压失败

### ISSUE THREAD

**Issue by yujia1996** [Haoran-SONG/PiP-Planning-informed-Prediction#4]
你好，我在你给其他人回复的链接里下载三个数据集 但都是解压失败 是文件本身上传出错了吗 我已经试过好多次了，三个数据集都不行。。。。

**Comment by Haoran-SONG** [comment]
> 你好，我在你给其他人回复的链接里下载三个数据集 但都是解压失败 是文件本身上传出错了吗 我已经试过好多次了，三个数据集都不行。。。。

传的都是源文件不需要解压, 不会有问题的. 你可以在这个[链接](https://hkustconnect-my.sharepoint.com/:f:/g/personal/hsongad_connect_ust_hk/Evo9MNDPLhZAn-ygM1-GOVQB-ULdHzx4WurTZ1j-Bk_JNQ?e=YdG7Xk)再试一下.
