### ISSUE TITLE
Questions about whether the project can be applied to real vehicles

### ISSUE THREAD

**Issue by mengqingyu123** [Haoran-SONG/PiP-Planning-informed-Prediction#5]
Thank you for your excellent work. Can the model trained in this project be used to predict real vehicles? In other words, can the LSTM-based architecture be used in real vehicles? Thank you!

**Comment by Haoran-SONG** [comment]
> Thank you for your excellent work. Can the model trained in this project be used to predict real vehicles? In other words, can the LSTM-based architecture be used in real vehicles? Thank you!

Regarding your question, my answer is yes, there exists more space to improve. As for the LSTM-based or other types of implementations, I think they are never the core point, but at least for this work, the methodology or the key idea matters. This work mainly focuses on the "problem formulation" of a prediction task, i.e., using candidate ego plans to inform the predictions of surrounding agents to achieve a closed-looped prediction-planning pipeline. 

From my viewpoint, besides the problem formulation, the other two aspects that are very essential for the prediction task are input representation, i.e., how to efficiently modeling the actor and map, and output representation, i.e., how to produce accurate, feasible trajectory prediction. An ideal prediction framework for autonomous driving, in my mind, should provide good convincing solutions in the above-mentioned aspects. 

If you're interested, I suggest taking a look at TNT [1] (with VectorNet) from Google & Waymo, as well as LaneGCN [2] from Uber ATG, which are good tries with different input representations. And my recent work [3] (this is not an ad ^_^) provides a brand new way of output representation. I hope you can find the answer from all these recent works. 

[1] "TNT: Target-driveN Trajectory Prediction"
[2] "LaneGCN: Learning Lane Graph Representations for Motion Forecasting"
[3] "Learning to Predict Vehicle Trajectories with Model-based Planning"

**Comment by mengqingyu123** [comment]
@Haoran-SONG Thank you for your answer. I feel that you are very funny and patient. Your answer is very helpful to me and supports me to continue in this line. Thanks again!
