### ISSUE TITLE
Trained models

### ISSUE THREAD

**Issue by qiran1122** [Haoran-SONG/PiP-Planning-informed-Prediction#7]
Hello, thank you very much for the source code for vehicle trajectory prediction. When I unzip the downloaded trained model ,there will always be errors. It has been solved for a long time without success. Can you send me a copy to my email “965845667@qq.com”? thank you.

**Comment by Haoran-SONG** [comment]
> Hello, thank you very much for the source code for vehicle trajectory prediction. When I unzip the downloaded trained model ,there will always be errors. It has been solved for a long time without success. Can you send me a copy to my email “[965845667@qq.com](mailto:965845667@qq.com)”? thank you.

That's the model itself, just ending with tar. You can load it directly without unzipping.

**Comment by LoveYuxiaoyu** [comment]
thanks!
