### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by kuanchih1993** [Haoran-SONG/PiP-Planning-informed-Prediction#8]
Thanks for your awesome work!
I'd like to ask about training time?
I found it takes me about 5 hours for one epoch.
Is it right?
Thanks!

**Comment by Haoran-SONG** [comment]
I didn't record it precisely but it costs nearly so long, if training with one GPU.

**Comment by Haoran-SONG** [comment]
> Thanks for your awesome work! I'd like to ask about training time? I found it takes me about 5 hours for one epoch. Is it right? Thanks!


I didn't record it precisely but it costs nearly so long, if training with one GPU.
