### ISSUE TITLE
 可视化预测结果

### ISSUE THREAD

**Issue by chengshuai** [Haoran-SONG/PiP-Planning-informed-Prediction#9]
您好：
    非常棒的工作并且开源了代码。
    想问下是否可开源预测结果可视化的代码？非常感谢。

**Comment by Haoran-SONG** [comment]
之前有过一个类似issue的回复
https://github.com/Haoran-SONG/PiP-Planning-informed-Prediction/issues/6#issuecomment-815500989

上面是colorbar的参考，然后gif是从图片生成的。因为当时觉着这些只是一些辅助的东西就没整理，只是用了matplotlib里面一些基础函数。
